### ISSUE TITLE
Setup commands lead to $Failed

### ISSUE THREAD

**Issue by uukhas** [WolframResearch/codeformatter#1]
After running the following commands:
```wolfram
PacletInstall["CodeParser"]
PacletInstall["CodeFormatter"]
Needs["CodeFormatter`"]
CodeFormat["If[a,f/@b,g/@c]"]
```
the output if the following:
![image](https://user-images.githubusercontent.com/48713304/141269165-014264f3-f3ad-479c-9d2c-4951323b672d.png)
![image](https://user-images.githubusercontent.com/48713304/141269241-aa3f46d0-0441-4eaf-9cf3-e113970f1b2b.png)
![image](https://user-images.githubusercontent.com/48713304/141269258-70041d4d-e254-407a-9a7f-8766b994632a.png)
```wolfram
$Failed
```

I have the following Mathematica version and system :
12.0.0 for Linux x86 (64-bit) (April 7, 2019)

**Comment by bostick** [comment]
Thank you for including the version!

Technically, versions before 12.1 are unsupported due to compatibility changes, and they are explained here:
https://github.com/WolframResearch/codeparser/blob/master/docs/compatibility.md

But it should be completely fine to build CodeParser from source with the Mathematica version that you will be using, by following the instructions here:
https://github.com/WolframResearch/codeparser/blob/master/HowToBuild.md

Please let me know how that goes.

**Comment by uukhas** [comment]
Thank you for a fast reply and the links!
I tried to follow the build guide and got the following error during the build (for the command `cmake ..`):
```bash
CMake Error at cmake/WolframKernel.cmake:40 (message):
  WOLFRAMKERNEL does not exist.  WOLFRAMKERNEL:
/usr/local/Wolfram/Mathematica/12.3/Executables/WolframKernel
```
It was fixed by the explicit change of `12.3` to `12.0` in the `build/CMakeCache.txt` file.
The following warning appeared:
```bash
CMake Warning at CMakeLists.txt:147 (message):
  VERSION_NUMBER is below 1210; installing paclets via CMake may not work.
```

After running `PacletInstall` I got the following:
![image](https://user-images.githubusercontent.com/48713304/141349962-c0539ccd-c65d-4372-9254-2d7b5d64d8ae.png)
```mathematica
Paclet[CodeParser, 1.4, <>]
```
And I still get the same errors and output as before after running:
```mathematica
Needs["CodeFormatter`"]
CodeFormat["If[a,f/@b,g/@c]"]
```

**Comment by bostick** [comment]
You can make sure to not get the `WOLFRAMKERNEL does not exist.` error by specifying the path at configuration time:
```
cd codeparser
mkdir build
cd build
cmake -DMATHEMATICA_INSTALL_DIR=/usr/local/Wolfram/Mathematica/12.0 ..
cmake --build .
```

You should not have to muck about in `CMakeCache.txt` manually.


I think I mention in `compatibility.md`:
>
> Wolfram versions before 12.1 must build from sources to use CodeParser.
> 
> Manually modify WolframVersion in PacletInfo.wl to allow paclet installation.
>

This means either changing `CodeParser/PacletInfo.wl.in` before building or `CodeParser/PacletInfo.wl` after building:
>
> WolframVersion -> "12.1+",
>

needs to be:
>
> WolframVersion -> "12.0",
>

for you.

Since you are building the paclet and calling `PacletInstall`, then go ahead and change `CodeParser/PacletInfo.wl.in` before building.

**Comment by uukhas** [comment]
Thank you for your advice. I though, that the 
```
Manually modify WolframVersion in PacletInfo.wl to allow paclet installation.
```
was not really relevant for me, because, as I mentioned, the message was saying that:
```
The paclet CodeParser was successfully installed.
```

In the very end the following receipt **worked** for me:
* Modify `CodeParser/PacletInfo.wl.in`.
* Run the build sequence from above comment.
* Launch Mathematica and evaluate `PacletInstall["/path/to/build/paclet/CodeParser-1.4.paclet"]`.

Thank you for the help!

**Comment by bostick** [comment]
I will work to have better instructions and mention the confusing message from installing.

You are very welcome!
